In [1]:
import numpy as np
import pandas as pd
from scipy.stats import laplace
import scipy.stats
import psycopg2
from sklearn.metrics import mean_squared_error
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime
from datetime import timedelta  
import threading

In [2]:
param_dic = {
    "host"      : "localhost",
    "database"  : "bachelorBesoeg2014",
    "user"      : "postgres",
    "password"  : "password",
    "port"      : "5432"
}

def execRangeQuery(params_dic,dates):
    query = """
    SELECT
    sum(count_)
    FROM _775147
    WHERE
    time_ >= '{date0}'
    AND time_ <=  '{date1}'
    ;
    """.format(date0 = dates[0], date1 = dates[1])
    try:
        connection = psycopg2.connect(**params_dic)
        cursor = connection.cursor()
        cursor.execute(query)
        record = cursor.fetchall()
        return record
    except (Exception, psycopg2.Error) as error :
        connection = False
        print ("Error while connecting to PostgreSQL", error)
    finally:
        if(connection):
            cursor.close()
            connection.close()
            print("Executed query and closed connection.")

def execQuery(params_dic,query):
    try:
        connection = psycopg2.connect(**params_dic)
        cursor = connection.cursor()
        cursor.execute(query)
        record = cursor.fetchall()
        return record
    except (Exception, psycopg2.Error) as error :
        connection = False
        print ("Error while connecting to PostgreSQL", error)
    finally:
        if(connection):
            cursor.close()
            connection.close()
            print("Executed query and closed connection.")
#"""select count(*) as number_of_dates, count(DISTINCT  count_) as distinct_count from _775147;"""
query = """select time_ from _775147;"""
result = execQuery(param_dic, query)
dates = [(date[0]) for date in result]

query = """select count_ from _775147;"""
result = execQuery(param_dic, query)
"""
print(result)
print(type(result))
print(type(result[0]))
print((str(result[0][0])))
"""
counts = [(count[0]) for count in result]

Executed query and closed connection.
Executed query and closed connection.


In [3]:
def add_missing_dates(old_dates):
    start_date = dates[0]
    end_date = dates[-1]
    all_dates = pd.date_range(start = start_date, end = end_date).to_pydatetime().tolist()
    return [(date.date()) for date in all_dates]
    
def add_missing_counts(old_counts, old_dates, new_dates):
        """Adds 0 to the list of counts where there was missing dates
        Parameters:
        old_counts (list of int): List counts for each day with 
        old_dates (list of datetime.date): List of dates that is not countious
        Returns:
        List of countious starting with the first value of 
        """
        zip_iterator = zip(old_dates, old_counts)
        missing_dict =  dict(zip_iterator)
        all_counts = np.zeros(len(new_dates))
        for i, date in enumerate(new_dates):
            val = missing_dict.get(date, 0)
            all_counts[i] = val
            
        return all_counts

In [4]:
all_dates = add_missing_dates(dates)
all_counts =  add_missing_counts(counts, dates, all_dates)

In [5]:
np.random.uniform(-1,0,1000)
def randomized_response(x, p=0.1):
    if np.random.uniform(0,1) < p:
        return x
    else:
        return np.random.randint(2)

In [6]:
randomized_response(1)

1

In [7]:
a = np.array([[0,1,2,3,4],[5,6,7,8,9],[0,1,2,3,4],[5,6,7,8,9],[0,1,2,3,4],[5,6,7,8,9]])

In [8]:
a[:,0]

array([0, 5, 0, 5, 0, 5])

In [9]:
epsilon = 0.6
print(1/(1+np.exp(epsilon)))

0.35434369377420455


In [10]:
class OUE:
    def __init__(self, epsilon):
        # We need the stream to be a power of 2
        self.epsilon = epsilon
        
    
    def process(self, e_i):
        o_i = e_i.copy()
        for idx, j in enumerate(e_i):
            if i == 1:
                o_i[idx] = np.random.randint(2)
            else:
                if np.random.uniform(0,1) < 1/(1+np.exp(epsilon)):
                    o_i[idx] = 1
                else:
                    o_i[idx] = 0
                    
    def aggreation(self, day, lst):
        return ( ( lst[:,day] +len(lst)/(1+np.exp(epsilon))) * (1/2 -1/(1+np.exp(epsilon))))
        
                

In [11]:
len(all_dates)
print(all_dates[0]-all_dates[-1])

-2005 days, 0:00:00


In [12]:
oue_count_lock = threading.Lock()
oue_count_lock.acquire()
oue_count_lock.release()

In [14]:
#len(oue_count)

In [15]:
def OUE_func_2(e_i, epsilon):
    #print('Call')
    #print(e_i)
    if e_i == 1:
        #print('if')
        return np.random.randint(2)
    else:
        #print('else')
        if np.random.uniform(0,1) < 1/(1+np.exp(epsilon)):
            return 1
        else:
            return 0

In [16]:
def OUE_answear(data, i, epsilon):
    return (data[i]/len(data) + len(data)/(1+np.exp(epsilon))) / (1/2 -1/(1+np.exp(epsilon)))

In [17]:
D = len(all_dates) 
oue_count = np.zeros(D)

In [18]:

vfunc = np.vectorize(OUE_func_2, otypes = [int])
epsilon = 1
vfunc([0,1,1,1,1], epsilon)
for idx, count in enumerate(all_counts):
    #print(idx)
    #print(count)
    for i in range(0,int(count)):
        sparse = np.zeros(D)
        sparse[idx] = 1
        dense = vfunc(sparse,epsilon)
        oue_count = oue_count + dense

KeyboardInterrupt: 

In [19]:
print(idx)
print(count)
print(i)

4
293.0
79


In [20]:
print(oue_count)

[198. 180. 155. ... 167. 145. 157.]


In [21]:
#np.savetxt('oue_count.csv', oue_count, delimiter=',')

In [22]:
print(( oue_count[0] +len(oue_count)/(1+np.exp(epsilon))) * (1/2 -1/(1+np.exp(epsilon))))

170.40489101704847


In [23]:
vfunc = np.vectorize(OUE_func_2, otypes = [int])
vfunc([0,1,1,1,1], 0.2)

array([1, 0, 1, 1, 1])

In [24]:
epsilon = 1
np.exp(epsilon)+1

3.718281828459045

In [25]:
def OUE_func(e_i, epsilon):
    o_i = e_i.copy()
    for idx, j in enumerate(e_i):
        if j == 1:
            o_i[idx] = np.random.randint(2)
        else:
            if np.random.uniform(0,1) < 1/(1+np.exp(epsilon)):
                o_i[idx] = 1
            else:
                o_i[idx] = 0
    return o_i

In [26]:
class flat_OUE:
    def __init__(self, epsilon, dates, counts):
        
        self.dates = dates
        self.real_counts = counts
        self.epsilon = epsilon
        self.counts = self.process(dates, counts)
        self.D = len(dates)
        
        values = np.arange(0,len(self.dates))
        zip_iterator = zip(self.dates, values)
        self.idx_dict =  dict(zip_iterator)
    
    def process(self, dates, counts):        
        vfunc = np.vectorize(OUE_func_2, otypes = [int])
        for idx, count in enumerate(all_counts):
            for i in range(0,int(count)):
                sparse = np.zeros(D)
                sparse[idx] = 1
                dense = vfunc(sparse,self.epsilon)
                oue_count = oue_count + dense
        return oue_count
    
    def answer(self, dates):
        
        if (len(dates) < 2):
                date_obj_0 = datetime.strptime(dates[0],'%Y-%m-%d').date()
                #print(date_obj_0)
                #print(type(date_obj_0))
                idx = self.idx_dict[date_obj_0]
                return self.noise_counts[idx]
            
            else:
                date_obj_0 = datetime.strptime(dates[0],'%Y-%m-%d').date()
                date_obj_1 = datetime.strptime(dates[1],'%Y-%m-%d').date()
                idx_0 = self.idx_dict[date_obj_0]
                idx_1 = self.idx_dict[date_obj_1]

                #idx_0 is not 0
                if idx_0:
                    return self.noise_counts[idx_1] - self.noise_counts[idx_0-1]            
                else:
                    return self.noise_counts[idx_1]

In [27]:
def OLH_func(x, epsilon, g):
    if np.random.uniform(0,1) < np.exp(epsilon)/(np.exp(epsilon)+g-1):
        #print('if')
        return x
    else:
        return np.random.randint(low = 0, high = g)
    
def OLH_answer(data, j, epsilon, N, g):
    p = np.exp(epsilon)/(np.exp(epsilon)+g-1)
    print(p - 1/g)
    return (data[j]- N/g) / (p - 1/g)

In [28]:
epsilon = 0.7
g = 2005
print(np.exp(epsilon)/(np.exp(epsilon)+g+1))

0.0010028580256262031


In [30]:
D = len(all_dates) 
OLH_count = np.zeros(D)

In [37]:
epsilon = 1
for idx, count in enumerate(all_counts):
    for i in range(0,int(count)):
        response = OLH_func(idx, epsilon, D)
        OLH_count[response] = OLH_count[response] + 1

In [48]:
print(OLH_count)
print(np.sum(OLH_count))
print(OLH_answer(OLH_count, 2005, epsilon, np.sum(OLH_count), D))
#N = np.sum(all_counts)
N = len(all_counts)
print(f'var should be {4*np.exp(epsilon) / (N*np.exp(epsilon) - N)**2}')

[833. 826. 843. ... 833. 846. 813.]
1677572.0
0.000855411475206737
-27211.66265497057
var should be 9.151743117683762e-07


In [40]:
np.sum(all_counts)

419393.0

In [49]:
#all_dates[0:100]

In [50]:
#print(all_counts[0:100])

In [51]:
my_data = np.genfromtxt('oue_count.csv', delimiter=',')

In [52]:
my_data

array([112676., 113258., 113340., ..., 112793., 113254., 112382.])

In [53]:
epsilon = 1
print( (my_data[0]/len(my_data) + len(my_data)/(1+np.exp(epsilon))) / (1/2 -1/(1+np.exp(epsilon))) )
print(OUE_answear(my_data, 0, epsilon))

2577.9868738285472
2577.9868738285472


In [54]:
print(len(my_data))
print(len(all_dates))

2006
2006
