In [9]:
import numpy as np
import pandas as pd
from scipy.stats import laplace
import scipy.stats
import psycopg2
from sklearn.metrics import mean_squared_error
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime

import math

In [4]:
def get_index(date_idx, n_layers, degree):
    """Calculates the path of index in full binary string

    Parameters:
    date_idx (int): The node in the bouttom layer we want to calculate a path to. 
    The bottom layer has index from 0 to 2**h-1
    n_layers (int): The height of the full binary tree. 

    Returns:
    list: of index in the path from the starting from the bottom and going up

    """
    idx = []
    for i in np.arange(0,n_layers):
        if i == 0:
            idx.append(int(date_idx))
        else:
            idx.append(int(idx[i-1]//degree))
    idx.append(0)
    return idx

In [5]:
print(get_index(0,1,3))
print(get_index(0,2,3))
print(get_index(0,3,3))
print(get_index(12,3,3))
print(get_index(15,3,3))
print(get_index(9,3,3))

[0, 0]
[0, 0, 0]
[0, 0, 0, 0]
[12, 4, 1, 0]
[15, 5, 1, 0]
[9, 3, 1, 0]


In [289]:
print(get_index(12,3,4))


[12, 3, 0, 0]


In [274]:
def get_group(idx, n_layers, degree, level):
    """Calculates the path of index in full binary string

    Parameters:
    date_idx (int): The node in the bouttom layer we want to calculate a path to. 
    The bottom layer has index from 0 to 2**h-1
    n_layers (int): The height of the full binary tree. 0 index

    Returns:
    list: of index in the path from the starting from the bottom and going up

    """
    if level == 0:
        return id
    elif idx == 0:
        return np.arange(0,degree)
    else:
        #print(degree**2)
        #print(int(np.log(idx) / np.log(degree))+1)
        #print('Group index')
        group_index = idx //degree
        #print(group_index)
        #print(math.log(idx,degree))
        #print(int(np.log(idx+degree) / np.log(degree))+1)
        #print('Possi')
        #print(level**degree)
        #Array of index at level
        level_indicis = np.arange(0,degree**level)
        #print(level_indicis)
        split_ratio = (len(level_indicis) // degree)
        #print(f'split_ratio = {split_ratio}')
        level_indicis_split = np.array_split(level_indicis, split_ratio)
        #print(level_indicis_split)
        #print(level_indicis_split[idx //degree])
        
        return level_indicis_split[group_index]

def turns_right(path, degree):
    #print(path)
    #0 is left 1 is right
    direction_lst = []
    for i in range(len(path)-1):
        #print(f'i = {i}')
        current = path[i]
        nxt = path[i+1]
        #print(f'current = {current}, nxt = {nxt}')
        if nxt == 0:
            #We went left
            #print('nxt == 0')
            direction_lst.append(0)
        elif current == 0 and current < nxt:
            #We went right
            #print('current == 0 and current < nxt')
            direction_lst.append(1)
        elif degree * current < nxt:
            #We went right
            #print('2* current < nxt')
            direction_lst.append(1)
        else:
            #print('else')            
            direction_lst.append(0)
            
    return direction_lst

def turns_left(path, degree):
    #print(path)
    #0 is left 1 is right
    direction_lst = []
    for i in range(len(path)-1):
        #print(f'i = {i}')
        current = path[i]
        nxt = path[i+1]
        print(f'current = {current}, nxt = {nxt}')
        #Checks
        if nxt == 0:
            #We went left
            #print('nxt == 0')
            direction_lst.append(0)
        #Checks
        elif nxt == current*degree + degree - 1:
            #We went right
            #print(current * degree)
            print(current * degree + degree)
            print('current * degree != nxt')
            direction_lst.append(1)
        elif current == 0 and current < nxt:
            #We went left
            print('current == 0 and current < nxt')
            direction_lst.append(0)
        else:
            print('else')            
            direction_lst.append(0)
            
    return direction_lst

#p = [0, 1, 5, 23]
#p = [0, 1, 4, 19]
#p = [0, 3, 13, 55]
#print(turns_left(p, degree))
"""
Paths
[ 0  1  5 23]
current = 0, nxt = 1
current == 0 and current < nxt
current = 1, nxt = 5
current * degree != nxt
current = 5, nxt = 23
current * degree != nxt
Turns
[1, 1, 1]

"""

current = 0, nxt = 3
4
current * degree != nxt
current = 3, nxt = 13
else
current = 13, nxt = 55
56
current * degree != nxt
[1, 0, 1]


'\nPaths\n[ 0  1  5 23]\ncurrent = 0, nxt = 1\ncurrent == 0 and current < nxt\ncurrent = 1, nxt = 5\ncurrent * degree != nxt\ncurrent = 5, nxt = 23\ncurrent * degree != nxt\nTurns\n[1, 1, 1]\n\n'

In [128]:
degree = 4
n_layers = 3
print(get_index(0, n_layers, degree))
print(get_index(32, n_layers, degree))


[0, 0, 0, 0]
[32, 8, 2, 0]


In [281]:


hhs = [[3241], [833, 843, 812, 823], [181, 200, 199, 219, 170, 217, 205,
        202, 221, 184, 213, 182, 211, 210, 173, 208],[56, 47, 60, 50, 56,
        62, 62, 51, 61, 47, 52, 41, 54, 63, 45, 46, 38, 46, 52, 53, 59, 58,
        48, 46, 41, 48, 33, 48, 58, 44, 38, 49, 46, 60, 37, 65, 59, 49, 70,
        56, 48, 50, 53, 53, 37, 46, 62, 55, 42, 50, 40, 49, 44, 52, 55, 59,
        49, 61, 43, 49, 51, 63, 55, 51]]
hhs = [np.array(a) for a in hhs]
print(hhs)
"""
hhs = [[1175], [420, 405, 412,], [123, 133, 116, 139, 136, 144, 146, 125, 113,],
[62, 44, 30, 39, 44, 41, 46, 54, 32, 41, 35, 45, 54, 48, 44, 43, 44, 41,
 41, 45, 41, 42, 38, 53, 39, 49, 49,]]
hhs = [np.array(a) for a in hhs]
print(hhs)
"""

[array([3241]), array([833, 843, 812, 823]), array([181, 200, 199, 219, 170, 217, 205, 202, 221, 184, 213, 182, 211,
       210, 173, 208]), array([56, 47, 60, 50, 56, 62, 62, 51, 61, 47, 52, 41, 54, 63, 45, 46, 38,
       46, 52, 53, 59, 58, 48, 46, 41, 48, 33, 48, 58, 44, 38, 49, 46, 60,
       37, 65, 59, 49, 70, 56, 48, 50, 53, 53, 37, 46, 62, 55, 42, 50, 40,
       49, 44, 52, 55, 59, 49, 61, 43, 49, 51, 63, 55, 51])]


'\nhhs = [[1175], [420, 405, 412,], [123, 133, 116, 139, 136, 144, 146, 125, 113,],\n[62, 44, 30, 39, 44, 41, 46, 54, 32, 41, 35, 45, 54, 48, 44, 43, 44, 41,\n 41, 45, 41, 42, 38, 53, 39, 49, 49,]]\nhhs = [np.array(a) for a in hhs]\nprint(hhs)\n'

In [288]:
degree = 4
n_layers = 3


idx_0 = 0
#14 #5 #8 FOR DEGREE TRE
#15, 23, 31 
idx_1 = 11 

#print(get_index(idx_0, n_layers, degree))
#print(get_index(idx_1, n_layers, degree))

idx_left = idx_0-1
idx_right = idx_1+1

path_to_left = np.flip(np.array(get_index(idx_left,n_layers, degree)))
path_to_right = np.flip(np.array(get_index(idx_right,n_layers, degree)))
print('Paths')
print(path_to_left)
print(path_to_right)
#Starting in 0
if idx_0 == 0:
    left_or_right_list_leftside = turns_right(path_to_left[path_to_right != path_to_left], degree)
    #print(left_or_right_list(path_to_left, degree))
    print(turns_right(path_to_right, degree))
    #left_or_right_list_rightside = left_or_right_list(path_to_right[path_to_right != path_to_left], degree)
    left_or_right_list_rightside = turns_right(path_to_right, degree)
    
    print('Turns')
    print(left_or_right_list_leftside)
    print(left_or_right_list_rightside)
    #level_offset = len(path_to_left)-len(left_or_right_list((np.array(path_to_left)[path_to_right != path_to_left]), degree))
    level_offset = 1
    print(f'level_offset = {level_offset}')
    """
    print('Finding the left side')
    for i in range(len(left_or_right_list_leftside)):
        #print(f'i = {i}')
        #print(left_or_right)
        print(f'We are looking at {left_or_right_list_leftside[i]}')
        if left_or_right_list_leftside[i] == 0:
            print(f'We are at level {i+level_offset}')
            print(path_to_left[i+level_offset])
            print('We went left')
            print('We need to count the right one')
            print(hhs[i+level_offset][path_to_left[i+level_offset]+1])
        else:
            print('We went right')
            print('Nothing to count')
    """
    print('-------------------------------')
    print('Finding the right side')
    for i in range(len(left_or_right_list_rightside)):
        #print(f'i = {i}')
        #print(left_or_right)
        print(f'We are looking at {left_or_right_list_rightside[i]}')
        if left_or_right_list_rightside[i] == 1:
            print(f'We are at level {i+level_offset}')
            print(f'We are at node {path_to_right[i+level_offset]} in the path')
            print('We went right')        
            print('We need to count the left one')
            group = get_group(path_to_right[i+level_offset],0 ,degree, i+level_offset)
            print(group)
            idx_sss = np.where(group == path_to_right[i+level_offset])[0][0]
            print(idx_sss)
            print(group[:idx_sss])
            
            count_nodes = hhs[i+level_offset][group[:idx_sss]]
            #print(count_nodes)
            for node in count_nodes:
                print(node)
            #print(hhs[i+level_offset][path_to_right[i+level_offset]-1])
        else:
            print('We went left')
            print('Nothing to count')
        
"""
"""
        
for level in hhs:
    print(level)

Paths
[ 0 -1 -1 -1]
[ 0  0  3 12]
[0, 1, 0]
Turns
[1, 1]
[0, 1, 0]
level_offset = 1
-------------------------------
Finding the right side
We are looking at 0
We went left
Nothing to count
We are looking at 1
We are at level 2
We are at node 3 in the path
We went right
We need to count the left one
[0 1 2 3]
3
[0 1 2]
181
200
199
We are looking at 0
We went left
Nothing to count
[3241]
[833 843 812 823]
[181 200 199 219 170 217 205 202 221 184 213 182 211 210 173 208]
[56 47 60 50 56 62 62 51 61 47 52 41 54 63 45 46 38 46 52 53 59 58 48 46
 41 48 33 48 58 44 38 49 46 60 37 65 59 49 70 56 48 50 53 53 37 46 62 55
 42 50 40 49 44 52 55 59 49 61 43 49 51 63 55 51]


In [279]:
degree = 3
n_layers = 3

#32 #48 #24 FOR DEGREE FOUR
idx_0 = 15

idx_1 = 26

#print(get_index(idx_0, n_layers, degree))
#print(get_index(idx_1, n_layers, degree))

idx_left = idx_0-1
idx_right = idx_1+1

path_to_left = np.flip(np.array(get_index(idx_left,n_layers, degree)))
path_to_right = np.flip(np.array(get_index(idx_right,n_layers, degree)))
print('Paths')
print(path_to_left)
print(path_to_right)
#For max
if idx_1 == 26:
    #left_or_right_list_leftside = turns_left(path_to_left[path_to_right != path_to_left], degree)
    left_or_right_list_leftside = turns_left(path_to_left, degree)
    #print(turns_left(path_to_left, degree))
    #print(left_or_right_list(path_to_right, degree))
    #left_or_right_list_rightside = left_or_right_list(path_to_right[path_to_right != path_to_left], degree)
    #left_or_right_list_rightside = turns_left(path_to_right, degree)
    
    print('Turns')
    print(left_or_right_list_leftside)
    #print(left_or_right_list_rightside)
    #level_offset = len(path_to_left)-len(left_or_right_list((np.array(path_to_left)[path_to_right != path_to_left]), degree))
    level_offset = 1
    print(f'level_offset  {level_offset}')
    print('Finding the left side')
    for i in range(len(left_or_right_list_leftside)):
        #print(f'i = {i}')
        #print(left_or_right)
        print(f'We are looking at {left_or_right_list_leftside[i]}')
        if left_or_right_list_leftside[i] == 0:
            print(f'We are at level {i+level_offset}')
            print(f'We are at node {path_to_left[i+level_offset]} in the path')
            print('We went left')
            print('We need to count the right one')
            group = get_group(path_to_left[i+level_offset], 0 ,degree, i+level_offset)
            print(group)
            idx_sss = np.where(group == path_to_left[i+level_offset])[0][0]
            print(idx_sss)
            print(group[idx_sss+1:])
            print(hhs[i+level_offset][group[idx_sss+1:]])
            print(hhs[i+level_offset][path_to_left[i+level_offset]+1])
        else:
            print('We went right')
            print('Nothing to count')
    """
    print('-------------------------------')
    print('Finding the right side')
    for i in range(len(left_or_right_list_rightside)):
        #print(f'i = {i}')
        #print(left_or_right)
        print(f'We are looking at {left_or_right_list_rightside[i]}')
        if left_or_right_list_rightside[i] == 1:
            print(f'We are at level {i+level_offset}')
            print(f'We are at node {path_to_right[i+level_offset]} in the path')
            print('We went right')        
            print('We need to count the left one')
            group = get_group(path_to_right[i+level_offset],0 ,degree, i+level_offset)
            print(group)
            idx_sss = np.where(group == path_to_right[i+level_offset])[0][0]
            print(idx_sss)
            print(group[:idx_sss])
            print(hhs[i+level_offset][group[:idx_sss]])
            print(hhs[i+level_offset][path_to_right[i+level_offset]-1])
        else:
            print('We went left')
            print('Nothing to count')
    """
        
"""
"""
        
for level in hhs:
    print(level)

Paths
[ 0  1  4 14]
[ 0  3  9 27]
current = 0, nxt = 1
current == 0 and current < nxt
current = 1, nxt = 4
else
current = 4, nxt = 14
15
current * degree != nxt
Turns
[0, 0, 1]
level_offset  1
Finding the left side
We are looking at 0
We are at level 1
We are at node 1 in the path
We went left
We need to count the right one
[0 1 2]
1
[2]
[412]
412
We are looking at 0
We are at level 2
We are at node 4 in the path
We went left
We need to count the right one
[3 4 5]
1
[5]
[144]
144
We are looking at 1
We went right
Nothing to count
[1175]
[420 405 412]
[123 133 116 139 136 144 146 125 113]
[62 44 30 39 44 41 46 54 32 41 35 45 54 48 44 43 44 41 41 45 41 42 38 53
 39 49 49]


In [117]:
"""
print(get_group(0,1,3,0))
print(get_group(0,2,3,0))
print(get_group(0,3,3,0))
print(get_group(12,3,3,0))
print(get_group(15,3,3,0))
"""
degree = 3
n_layers = 3
#print(get_group(0,n_layers, degree, 2))
#print(get_group(9,3,3,3))
#print(get_group(12,3,3,3))
#print(get_group(21,3,3,3))
print(get_group(3, n_layers, degree, 2))
print(get_group(21, n_layers, degree, 3))
print(get_group(9, n_layers, degree, 4))
#print(get_group(3,3,3,2))
#print(get_group(10,3,3,3))

[3 4 5]
[21 22 23]
[ 9 10 11]


In [124]:
degree = 4
n_layers = 3
print(get_group(4, n_layers, degree, 2))
print(get_group(24, n_layers, degree, 3))
degree = 2
n_layers = 3
print(get_group(1, n_layers, degree, 2))
print(get_group(2, n_layers, degree, 3))

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11]), array([12, 13, 14, 15])]
[4 5 6 7]
[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11]), array([12, 13, 14, 15]), array([16, 17, 18, 19]), array([20, 21, 22, 23]), array([24, 25, 26, 27]), array([28, 29, 30, 31]), array([32, 33, 34, 35]), array([36, 37, 38, 39]), array([40, 41, 42, 43]), array([44, 45, 46, 47]), array([48, 49, 50, 51]), array([52, 53, 54, 55]), array([56, 57, 58, 59]), array([60, 61, 62, 63])]
[24 25 26 27]
[array([0, 1]), array([2, 3])]
[0 1]
[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7])]
[2 3]
